openapi: 3.0.1
info:
  title: Carritos
  description: Endpoints para la gestión de carritos en el sistema de ecommerce
  version: 1.0.0
paths:
  /api/carts:
    post:
      summary: Crea un nuevo carrito
      tags: [Carritos]
      security:
        - bearerAuth: []
      responses:
        201:
          description: Carrito creado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  cid:
                    type: string
                  message:
                    type: string
                    example: Carrito creado correctamente
        500:
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      summary: Obtiene todos los carritos
      tags: [Carritos]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Lista de carritos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cart'
        500:
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/carts/{cid}:
    get:
      summary: Obtiene un carrito por ID
      tags: [Carritos]
      parameters:
        - name: cid
          in: path
          description: ID del carrito
          required: true
          schema:
            type: string
      responses:
        200:
          description: Carrito encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        404:
          description: Carrito no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Elimina un carrito por ID
      tags: [Carritos]
      parameters:
        - name: cid
          in: path
          description: ID del carrito
          required: true
          schema:
            type: string
      responses:
        200:
          description: Carrito eliminado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Carrito eliminado correctamente
        404:
          description: Carrito no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/carts/{cid}/product/{pid}:
    post:
      summary: Agrega un producto al carrito
      tags: [Carritos]
      security:
        - bearerAuth: []
      parameters:
        - name: cid
          in: path
          description: ID del carrito
          required: true
          schema:
            type: string
        - name: pid
          in: path
          description: ID del producto
          required: true
          schema:
            type: string
      requestBody:
        description: Cantidad de productos a agregar
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  example: 1
      responses:
        200:
          description: Producto agregado al carrito
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                    example: Producto agregado exitosamente al carrito
                  cart:
                    $ref: '#/components/schemas/Cart'
        404:
          description: Producto o carrito no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        403:
          description: No autorizado para agregar producto al carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Actualiza la cantidad de un producto en el carrito
      tags: [Carritos]
      security:
        - bearerAuth: []
      parameters:
        - name: cid
          in: path
          description: ID del carrito
          required: true
          schema:
            type: string
        - name: pid
          in: path
          description: ID del producto
          required: true
          schema:
            type: string
      requestBody:
        description: Nueva cantidad del producto
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
      responses:
        200:
          description: Cantidad de producto actualizada en el carrito
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Cantidad actualizada correctamente
                  cart:
                    $ref: '#/components/schemas/Cart'
        404:
          description: Producto o carrito no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Elimina un producto del carrito
      tags: [Carritos]
      security:
        - bearerAuth: []
      parameters:
        - name: cid
          in: path
          description: ID del carrito
          required: true
          schema:
            type: string
        - name: pid
          in: path
          description: ID del producto
          required: true
          schema:
            type: string
      responses:
        200:
          description: Producto eliminado del carrito
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Producto eliminado exitosamente del carrito
                  cart:
                    $ref: '#/components/schemas/Cart'
        404:
          description: Producto o carrito no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/carts/{cid}/purchase:
    post:
      summary: Finaliza la compra de un carrito
      tags: [Carritos]
      security:
        - bearerAuth: []
      parameters:
        - name: cid
          in: path
          description: ID del carrito
          required: true
          schema:
            type: string
      responses:
        200:
          description: Compra finalizada con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                    example: Compra finalizada con éxito
                  totalAmount:
                    type: number
                  ticketId:
                    type: string
        206:
          description: Compra parcialmente exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                    example: Compra parcialmente exitosa
                  totalAmount:
                    type: number
                  ticketId:
                    type: string
                  failedProducts:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        _id:
                          type: string
        500:
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Cart:
      type: object
      properties:
        id:
          type: string
        products:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
              quantity:
                type: integer
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: integer
